name: Build Artifacts for Staging Environment

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

env:
  REPO_NAME_OLD: rudderlabs/rudder-transformer
  REPO_NAME: rudderstack/rudder-transformer
  DOCKERHUB_USERNAME: rudderlabs

jobs:
  build-transformer-image:
    name: Build Transformer Docker Image - Staging
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gen_img_version.outputs.version }}

    # Only pull requests from release candidate branches must trigger
    if: (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix-release/'))
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Generate Image Version
        id: gen_img_version
        run: |
          VERSION="staging-$(jq -r .version package.json)"
          echo $VERSION
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PROD_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          load: true
          tags: |
            ${{ env.REPO_NAME }}:${{ steps.gen_img_version.outputs.version }}

      - name: Run Tests
        run: |
          docker run ${{ env.REPO_NAME }}:${{ steps.gen_img_version.outputs.version }} npm run test:ci

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Multi-platform Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REPO_NAME_OLD }}:${{ steps.gen_img_version.outputs.version }}
            ${{ env.REPO_NAME }}:${{ steps.gen_img_version.outputs.version }}
            ${{ env.REPO_NAME }}:latest
            ${{ env.REPO_NAME_OLD }}:latest
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            VERSION=${{ steps.gen_img_version.outputs.version }}
            COMMIT_HASH=${{ github.sha }}

  build-user-transformer-image:
    name: Build User Transformer Docker Image - Staging
    runs-on: ubuntu-latest
    outputs:
      ut-version: ${{ steps.gen_img_version.outputs.version }}

    # Only pull requests from release candidate branches must trigger
    if: (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix-release/'))
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Generate Image Version
        id: gen_img_version
        run: |
          VERSION="staging-ut-$(jq -r .version package.json)"
          echo $VERSION
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PROD_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-ut-func
          load: true
          tags: |
            ${{ env.REPO_NAME }}:${{ steps.gen_img_version.outputs.version }}

      - name: Run Tests
        run: |
          docker run ${{ env.REPO_NAME }}:${{ steps.gen_img_version.outputs.version }} npm run test:ci

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Multi-platform Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-ut-func
          push: true
          tags: |
            ${{ env.REPO_NAME_OLD }}:${{ steps.gen_img_version.outputs.version }}
            ${{ env.REPO_NAME }}:${{ steps.gen_img_version.outputs.version }}
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            VERSION=${{ steps.gen_img_version.outputs.version }}
            COMMIT_HASH=${{ github.sha }}

  create-pull-request:
    name: Update Helm Charts For Staging and Create Pull Request
    runs-on: ubuntu-latest
    needs: [ build-transformer-image, build-user-transformer-image ]
    env:
      VERSION: ${{ needs.build-transformer-image.outputs.version }}
      UT_VERSION: ${{ needs.build-user-transformer-image.outputs.version }}
    steps:
      - name: Print Docker Image Versions
        run: |
          echo "Transformer: $VERSION"
          echo "User Transformer: $UT_VERSION"

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize Mandatory Git Config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"

      - name: Check Branch Exists
        id: check-branch-exists
        run: |
          BRANCH_NAME="shared-transformer-$VERSION"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          if [ `git ls-remote --heads origin $BRANCH_NAME 2>/dev/null` ]
          then
            echo "BRANCH_EXISTS=\"1\"" >> $GITHUB_OUTPUT
          else
            echo "BRANCH_EXISTS=\"0\"" >> $GITHUB_OUTPUT
          fi

      - name: Clone rudder-devops
        if: steps.check-branch-exists.outputs.BRANCH_EXISTS == '0'
        run: |
          git clone https://${{secrets.PAT}}@github.com/rudderlabs/rudder-devops.git
          cd rudder-devops
          git checkout -b $BRANCH_NAME

      - name: Update Helm Charts
        if: steps.check-branch-exists.outputs.BRANCH_EXISTS == '0'
        run: |
          cd helm-charts/shared-services/per-az
          yq eval -i ".rudder-transformer.image.tag=\"$VERSION\"" values.staging.yaml
          yq eval -i ".user-transformer.image.tag=\"$UT_VERSION\"" values.staging.yaml
          git add values.staging.yaml

          cd ../../config-be-rudder-transformer
          yq eval -i ".config-be-rudder-transformer.image.tag=\"$VERSION\"" values.staging.yaml
          yq eval -i ".config-be-user-transformer.image.tag=\"$UT_VERSION\"" values.staging.yaml
          git add values.staging.yaml

      - name: Create Pull Request
        if: steps.check-branch-exists.outputs.BRANCH_EXISTS == '0'
        run: |
          git commit -m "chore: upgrade staging env transformers to \"$VERSION\""
          git push -u origin $BRANCH_NAME"
          hub pull-request -m "chore: upgrade staging env transformers to \"$VERSION\""
