name: Build transformer release image
on:
  push:
    branches:
      - "rudder-saas"
env:
  REPO_NAME: rudderlabs/rudder-transformer

jobs:
  user-transformer-build:
    name: Build user transformer image
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get image version
        id: get_version
        run: |
          VERSION="ut-$(date '+%d%m%Y.%H%M%S')"
          echo $VERSION          
          echo "::set-output name=version::$VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rudderlabs
          password: ${{ secrets.DOCKERHUB_PROD_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-ut-func
          load: true
          tags: ${{ env.REPO_NAME }}:${{ steps.get_version.outputs.version }}

      - name: Run Tests
        run: |
          docker run ${{ env.REPO_NAME }}:${{ steps.get_version.outputs.version }} npm run test

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-ut-func
          push: true
          tags: ${{ env.REPO_NAME }}:${{ steps.get_version.outputs.version }}
          build-args: |
            VERSION=${{ steps.get_version.outputs.version }}
            COMMIT_HASH=${{ github.sha }}
  # TODO: Add Dest transformer build job after codebuild is removed
