name: codacy-coverage-reporter

on: push

jobs:
  install-and-test:
    name: install and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/setup-node@v2
      with:
        node-version: 10
      run: npm install
    - name: Jest
      uses: rkusa/jest-action@master
      with:
        secrets: d10e6be8dedb20348a882bf1aa92423d6ec22276
